config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#welcome'

  get '/signup', to: 'users#new' # don't need a post signup, since our users resource already has one
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home', to: 'users#index'
  get '/ordered_comments', to: 'comments#ordered_comments'

  # google oauth callback route
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :comments
  resources :projects do 
    resources :comments, only: [:index, :new, :create, :show]
  end
  resources :yarns, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :show]

  # this route matches any url that is invalid and will send to the not_found method in the application controller, which renders a 404 page.
  match '*path', to: 'application#not_found', via: [:get, :post]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :content, presence: true

  scope :ordered_comments, -> { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_permission, only: [:edit, :update, :destroy]

  def index
    # the only time this will get accessed is if someone views all comments for a project.
    set_project
  end

  def ordered_comments
    @comments = Comment.ordered_comments
    render :index
  end

  def new
    set_project
    @comment = @project.comments.build
  end

  def create
    @comment = current_user.comments.build(comment_params)
    # this line creates a new comment linked to a user without adding a 2nd line of code to do so separately. 
    if @comment.save
      redirect_to comment_path(@comment)
    else
      render :new 
    end
    
  end

  def show
    set_comment
  end

  def edit
    set_comment
  end

  def update
    comment = Comment.find_by(id: params[:id])
    comment.update(comment_params)
    flash[:message] = 'Comment updated successfully.'
    redirect_to project_comment_path(comment.project_id, comment.id)
  end

  def destroy
    comment = Comment.find_by(id: params[:id])
    project = comment.project_id
    comment.destroy
    flash[:message] = 'Comment successfully deleted.'
    redirect_to project_path(project)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :project_id)
  end

  def set_project
    @project = Project.find_by_id(params[:project_id])
  end

  def set_comment
    @comment = Comment.find_by_id(params[:id])
  end

  def require_permission
    comment = Comment.find_by(id: params[:id])
    if comment.user_id != current_user.id
      flash[:error] = 'Only the user who created a comment may edit or delete it.'
      redirect_to comment_path(comment)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
  <%= f.label :content %><br>
  <%= f.text_area :content %><br>

  <%= f.hidden_field :project_id %>
  <!-- carries over the project Id to the create action-->

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render partial: 'layouts/errors', locals: {object: @comment} %>

<%= form_for(@comment) do |f| %>
  <%= render 'form', f: f %>

  <%= f.submit 'Update Comment', class: 'submit-btn' %>
<% end %>

app/views/comments/index.html.erb
<h1>All Comments: </h1>

<% @comments.each do |comment| %>
  <div> 
    <h3><%= link_to comment.user.username, user_path(comment.user_id) %>: </h3>
    <p><%= comment.content %></p>
    <p><%= comment.created_at.strftime("Left on %-m/%-d/%Y") %></p>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment for <%= @comment.project.title %></h1>

<%= render partial: 'layouts/errors', locals: {object: @comment} %>

<%= form_for(@comment) do |f| %>
  <%= render 'form', f: f %>

  <%= f.submit 'Post Comment', class: 'submit-btn' %>
<% end %>

app/views/comments/show.html.erb
<h1>Review Your Comment:</h1>

<br>
<p><%= @comment.content %></p>
<br>
<% if @comment.user_id == current_user.id %>
  <%= link_to 'Edit this Comment', edit_comment_path(@comment), class: 'btn-link' %> 
  <%= link_to 'Delete this Comment', comment_path, method: :delete, class: 'btn-link' %> 
<% end %>
<%= link_to 'Back to Project Page', project_path(@comment.project), class: 'btn-link' %>