config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#welcome'

  get '/signup', to: 'users#new' # don't need a post signup, since our users resource already has one
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home', to: 'users#index'
  get '/ordered_comments', to: 'comments#ordered_comments'

  # google oauth callback route
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :comments
  resources :projects do 
    resources :comments, only: [:index, :new, :create, :show]
  end
  resources :yarns, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :show]

  # this route matches any url that is invalid and will send to the not_found method in the application controller, which renders a 404 page.
  match '*path', to: 'application#not_found', via: [:get, :post]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :yarns
  has_many :projects
  has_many :comments
  has_many :commented_projects, through: :comments, source: 'project'
  # has_many :projects, through: :comments
  has_one_attached :image

  has_secure_password
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true

  # scope method for finding the user who has made the most comments
  scope :top_commenter, -> { joins(:comments).group(:user_id).order('COUNT(comments.id) DESC').limit(1) }
  # joins users table to comments table, groups comments by user ID, counts the comments made by each user and puts them in descending order, then returns only the first one (the one with the highest number of comments)

  # method for creating/logging in a user via google oauth, called in the sessions controller
  def self.create_by_oauth(auth)
    self.find_or_create_by(email: auth[:info][:email]) do |u|
      u.password = SecureRandom.hex #sets a random password
      u.username = auth[:info][:name]
      u.email = auth[:info][:email]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def index
    @project = Project.popular_project.first
    @new_projects = Project.recent_projects
    @top_commenter = User.top_commenter.first
    @popular_yarn = Yarn.popular_yarn.first
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:message] = 'Account successfully created!'
      redirect_to home_path
    else
      render :new
    end
  end

  def show
    # set the user, then use the has_many relationship to show that user's yarns and projects in the view. That way it doesn't matter what user is logged in, the username, yarns, and projects in the view will always match the ID in the URL. 
    @user = User.find_by(id: params[:id])
    # finds the user's yarn and sorts the display table based on which heading the user selected.
    @yarns = @user.yarns.order(params[:sort])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Welcome to Yarn Stasher</h1>

<p>Here's what is going on in the app today:</p>

<div class="top-project">
  <h2>Most Popular Project</h2>
  <h3><%= link_to @project.title, project_path(@project) %></h3>
  <p><%= @project.user.username %></p>
</div>

<div class="top-brand">
  <h2>Most Popular Yarn Brand</h2>
  <h3><%= @popular_yarn.brand_name %></h3>
</div>

<div class="top-commenter">
  <h2>Top Commenter</h2>
  <h3><%= @top_commenter.username %></h3>
  <p>Total Comments: <%= @top_commenter.comments.count %></p>

</div>

<div class="new-projects">
  <h2>Recently Created Projects</h2>
  <div class="cards">
    <% @new_projects.each do |project| %>
      <div class="project-card">
        <h3><%= link_to project.title, project_path(project) %></h3>
        <p><%= project.user.username %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h2>

<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= form_for(@user) do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>

  <%= f.label :image %><br>
  <%= f.file_field :image %><br>

  <%= f.label :email %><br>
  <%= f.email_field :email%><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.submit 'Sign Up', class: 'submit-btn' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Stash</h1>


<% if @user.image.attached? %>
    <div class="avatar">
        <br>
        <%= image_tag url_for(@user.image) %>
        <br>
    </div>
<% end %>


<%= link_to 'Add New Yarn', new_yarn_path, class: 'btn-link' %>  <%= link_to 'Add New Project', new_project_path, class: 'btn-link' %>

<h2>My Yarns</h2>

<table>
    <thead>
        <tr>
            <th><%= link_to 'Brand', sort: 'brand_name' %></th>
            <th><%= link_to 'Colorway', sort: 'colorway' %></th>
            <th><%= link_to 'Fiber', sort: 'fiber' %></th>
            <th><%= link_to 'Weight', sort: 'weight' %></th>
            <th><%= link_to 'Yardage', sort: 'yardage' %></th>
            <th><%= link_to 'Quantity', sort: 'quantity' %></th>
        </tr>
    </thead>
    <% @yarns.each do |yarn|%>
        <tr>
            <td><%= link_to yarn.brand_name, yarn_path(yarn) %></td>
            <td><%= yarn.colorway %></td>
            <td><%= yarn.fiber %></td>
            <td><%= yarn.weight %></td>
            <td><%= yarn.yardage %></td>
            <td><%= yarn.quantity %></td>
            
        </tr>
    <% end %>
</table>

<h2>My Projects</h2>
<div class="cards">
    <% @user.projects.each do |project| %>
        <div class="project-card">
            <h3><%= link_to project.title, project_path(project) %></h3>
            <p>Pattern: <%= project.pattern_name %></p>
            <p>Designer: <%= project.designer %></p>
            <p>Craft: <%= project.craft %></p>
            <p>Tool Size: <%= project.tool_size %></p>
        </div>
    <% end %>
</div>