config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#welcome'

  get '/signup', to: 'users#new' # don't need a post signup, since our users resource already has one
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home', to: 'users#index'
  get '/ordered_comments', to: 'comments#ordered_comments'

  # google oauth callback route
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :comments
  resources :projects do 
    resources :comments, only: [:index, :new, :create, :show]
  end
  resources :yarns, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :show]

  # this route matches any url that is invalid and will send to the not_found method in the application controller, which renders a 404 page.
  match '*path', to: 'application#not_found', via: [:get, :post]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :yarns
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments

  accepts_nested_attributes_for :yarns

  validates :title, presence: true
  # finds the project with the highest humber of comments
  scope :popular_project, -> { joins(:comments).group(:project_id).order('COUNT(comments.id) DESC').limit(1) }
  # joins projects table to comments table, groups comments by project ID, counts the comments for each project ID and puts them in descending order, then returns only the first one (the one with the highest number of comments)

  # finds the 5 most recent projects
  scope :recent_projects, -> { order(created_at: :desc).limit(5) }
  # orders projects by their created_at date/time in descending order, then returns only the first 5 (the 5 most recently created projects)

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_permission, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = session[:user_id] 

    @project.save
    if @project.save
      flash[:message] = 'Project created successfully.'
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    set_project
  end

  def edit
    set_project
  end

  def update
    project = Project.find_by(id: params[:id])
    project.update(project_params)
    flash[:message] = 'Project updated successfully.'
    redirect_to project_path(project)
  end

  def destroy
    project = Project.find_by(id: params[:id])
    project.destroy
    flash[:message] = 'Project deleted successfully.'
    redirect_to user_path(current_user)
  end

  private

  def project_params
    params.require(:project).permit(:title, :pattern_name, :designer, :craft, :tool_size, :user_id, yarn_ids: [])
  end

  def require_permission
    project = Project.find_by(id: params[:id])
    if project.user_id != current_user.id
      flash[:error] = 'Only the user who created a project may edit or delete it.'
      redirect_to project_path(project)
    end
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :pattern_name %><br>
  <%= f.text_field :pattern_name %><br>

  <%= f.label :designer %><br>
  <%= f.text_field :designer %><br>

  <%= f.label :craft %><br>
  <%= f.text_field :craft %><br>

  <%= f.label :tool_size %><br>
  <%= f.text_field :tool_size %><br>

  <p>Select Yarn for Your Project:</p>
  <%= f.collection_select :yarn_ids,  current_user.yarns, :id, :brand_and_colorway, {include_blank: true}, {multiple: true} %><br>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render partial: 'layouts/errors', locals: {object: @project} %>

<%= form_for(@project) do |f| %>
  <%= render 'form', f: f %>

  <%= f.submit 'Update Project', class: 'submit-btn' %>
<% end %>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<% @projects.each do |project| %>
  <h2><%= link_to project.title, project_path(project) %></h2>
  <p>Crafter: <%= link_to project.user.username,  user_path(project.user_id) %><p>
<% end %>

app/views/projects/new.html.erb
<h1>Start a New Project</h1>

<%= render partial: 'layouts/errors', locals: {object: @project} %>


<%= form_for(@project) do |f| %>
  <%= render 'form', f: f %>

  <%= f.submit 'Start Project', class: 'submit-btn' %>
<% end %>

app/views/projects/show.html.erb
<% if @project.user == current_user %>
<%= link_to 'Edit This Project', edit_project_path(@project), class: 'btn-link' %>
<%= link_to 'Delete This Project', project_path(@project), method: :delete, class: 'btn-link' %>
<% end %>

<div class='project-info'>
  <h1><%= @project.title %></h1>
  <p>Crafter: <%= link_to @project.user.username,  user_path(@project.user_id) %></p>
  <p>Pattern Name: <%= @project.pattern_name %></p>
  <p>Designer: <%= @project.designer %></p>
  <p>Craft: <%= @project.craft %></p>
  <p>Tool Size: <%= @project.tool_size %></p>
</div>

<div class='yarns-info'>
  <h2>Yarns Used:</h2>
  <% if @project.yarns %>
    <% @project.yarns.each do |yarn| %>
      <p>Brand Name: <%= yarn.brand_name %></p>
      <p>Colorway: <%= yarn.colorway %></p>
      <p>Fiber: <%= yarn.fiber %></p>
      <p>Weight: <%= yarn.weight %></p>
      <p>Yardage: <%= yarn.yardage %></p>
      <p>Quantity: <%= yarn.quantity %></p>
    <% end %>
  <% end %>
</div>

<div class='comments-section'>
  <h2>Comments</h2>
  
  <%= link_to 'Leave a Comment', new_project_comment_path(@project.id), class: 'btn-link' %>
  <%= link_to 'View All Comments', project_comments_path(@project), class: 'btn-link' %>
  <br>
  <% @project.comments.each do |comment| %>
  <div class="comment-container">
    <h3><%= link_to comment.user.username, user_path(comment.user_id) %>: </h3>
    <p><%= comment.content %></p>
    <p class='timestamp'><%= comment.created_at.strftime("Left on %-m/%-d/%Y") %></p>
    <%= link_to 'View Comment', project_comment_path(@project, comment.id), class: 'btn-link' %>
  </div>
  <% end %>
</div>