config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#welcome'

  get '/signup', to: 'users#new' # don't need a post signup, since our users resource already has one
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home', to: 'users#index'
  get '/ordered_comments', to: 'comments#ordered_comments'

  # google oauth callback route
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :comments
  resources :projects do 
    resources :comments, only: [:index, :new, :create, :show]
  end
  resources :yarns, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :show]

  # this route matches any url that is invalid and will send to the not_found method in the application controller, which renders a 404 page.
  match '*path', to: 'application#not_found', via: [:get, :post]
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YarnStasherRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <nav>
      <% if logged_in %>
        <%= link_to 'Home', home_path %>
        <%= link_to 'My Profile', user_path(current_user) %>
        <%= link_to 'New Yarn', new_yarn_path %>
        <%= link_to 'New Project', new_project_path %>
        <%= link_to 'All Projects', projects_path %>
        <%= link_to 'Log Out', logout_path, method: :delete %>
      <% else %>
        <%= link_to 'Log In', login_path %> | 
        <%= link_to 'Sign Up', signup_path %>
      <% end %>
      <%= image_tag('logo.png', class: 'logo') %>
    </nav>
    <div class='wrapper'>
      <% if flash[:error] %>
        <div class='flash-error'>
          <%= flash[:error] %>
        </div>
      <% end %>

      <% if flash[:message] %>
        <div class='flash-message'>
          <%= flash[:message] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <footer class="branding">
      <small>&copy; 2021 <strong>Yarn Stasher</strong></small>
    </footer>
  </body>
</html>